
# cd larry/ && touch __init__.py agent.py
list:
    just -l

# Web
run-web:
    adk web
web:
    # RAILS_ROOT=`pwd`
    adk web

# With generic key. Note I have to move the JSON_SHEET_FILE back one folder.
run-trixie:
    GOOGLE_APPLICATION_CREDENTIALS="trixie/private/my-service-account-key.json" \
    JSON_SHEET_FILE="trixie/etc/sheets_config.json" \
    adk run trixie/


run-sql-agent:
    adk run siculo/
