

set dotenv-load
set export

# works because of set export
#PYTHONPATH := "./_common/lib:${PYTHONPATH}"
FOO := '4523452345'
#set list := 'listami'
a := "hello"

# Shows justfile targets
list:
    just -l
    @echo "PYTHONPATH=$PYTHONPATH"
    @echo "FOO=$FOO"

# Shows justfile code
cat:
    cat justfile

# Web
run-web:
    adk web --port 8080
web:
    # RAILS_ROOT=`pwd`
    adk web --port 8080

# With generic key. Note I have to move the JSON_SHEET_FILE back one folder.
run-trixie:
    GOOGLE_APPLICATION_CREDENTIALS="trixie/private/my-service-account-key.json" \
    JSON_SHEET_FILE="trixie/etc/sheets_config.json" \
    adk run trixie/


run-sql-agent:
    adk run siculo/

run-wikipedia-agent:
    adk run vicky/

run-claudia-agent:
    echo Try: Show me GCE VMs
    adk run claudia/

run-serpeverde-agent:
    PYTHONPATH="./_common/lib:$PYTHONPATH"
    echo This is to test _common/ code
    PYTHONPATH="./_common/lib:$PYTHONPATH" adk run serpeverde/

test-claudia-agent:
    echo Show me GCE VMs | adk run claudia/

find-python-and-env-files:
    find . -name \*.py -o -name .env



##############
# Unit Tests
##############

test-common-lib-serper-tools:
    python -m unittest _common.lib.serper_tools_test

test: test-common-lib-serper-tools
    echo Testing ALL
