

set dotenv-load
set export

# works because of set export
#PYTHONPATH := "./_common/lib:${PYTHONPATH}"
FOO := '4523452345'
#set list := 'listami'
a := "hello"

# Shows justfile targets
list:
    just -l
    @echo "PYTHONPATH=$PYTHONPATH"
    @echo "FOO=$FOO"

# Shows justfile code
cat:
    cat justfile

# Web
run-web:
    adk web --port 8080
web:
    # RAILS_ROOT=`pwd`
    adk web --port 8080

# With generic key. Note I have to move the JSON_SHEET_FILE back one folder.
run-trixie:
    GOOGLE_APPLICATION_CREDENTIALS="trixie/private/my-service-account-key.json" \
    JSON_SHEET_FILE="trixie/etc/sheets_config.json" \
    adk run trixie/


run-sql-agent:
    adk run siculo/

run-wikipedia-agent:
    adk run vicky/

run-claudia-agent:
    echo Try: Show me GCE VMs
    adk run claudia/

run-serpeverde-agent:
    PYTHONPATH="./_common/lib:$PYTHONPATH"
    echo This is to test _common/ code
    PYTHONPATH="./_common/lib:$PYTHONPATH" adk run serpeverde/

test-claudia-agent:
    echo Show me GCE VMs | adk run claudia/

find-python-and-env-files:
    find . -name \*.py -o -name .env

##############
# Deployments
##############
# [deploy] Deploys SQL Agent to Riccardo Cloud Run project
push-sql-to-cloud-run:
    siculo/bin/create_sample_db.sh siculo/cloud_run_pushable_db.sqlite
    # adk deploy cloud_run siculo/ --region europe-west1 --help
    adk deploy cloud_run siculo/ --region europe-west1 --project ricc-genai --service_name siculo --with_ui
    # => https://siculo-794266741446.europe-west1.run.app
    # Now you need to set ENV variables.

push-larry-to-cloud-run:
    adk deploy cloud_run larry/ --region europe-west1 --project ricc-genai --service_name adk-larry --with_ui --trace_to_cloud
    gcloud --project ricc-genai run services add-iam-policy-binding adk-larry \
        --member="user:ricc@google.com" \
        --role="roles/run.invoker" --region europe-west1
    gcloud --project ricc-genai run services add-iam-policy-binding adk-larry \
        --member="user:strebel@google.com" \
        --role="roles/run.invoker" --region europe-west1

# [deploy] Deploys SQL Agent to Riccardo Cloud Run project
iam-give-access-to-ricc:
    gcloud --project ricc-genai  run services add-iam-policy-binding siculo \
        --member="user:ricc@google.com" \
        --role="roles/run.invoker" --region europe-west1
    gcloud --project ricc-genai  run services add-iam-policy-binding siculo \
        --member="user:strebel@google.com" \
        --role="roles/run.invoker" --region europe-west1
    # Note to self: This is failing with
    #    ERROR: (gcloud.run.services.add-iam-policy-binding) FAILED_PRECONDITION: One or more users named in the policy do not belong to a permitted customer,
    #           perhaps due to an organization policy.
    # Most likely an internal Org Policy.
    gcloud --project ricc-genai  run services add-iam-policy-binding siculo \
        --member="user:palladiusbonton@gmail.com" \
        --role="roles/run.invoker" --region europe-west1
    echo We love our GDEs..
    gcloud --project ricc-genai  run services add-iam-policy-binding siculo \
        --member="user:maurizio.ipsale@gmail.com" \
        --role="roles/run.invoker" --region europe-west1


##############
# Unit Tests
##############

test-common-lib-serper-tools:
    python -m unittest _common.lib.serper_tools_test

test: test-common-lib-serper-tools
    echo Testing ALL
