
# This list here
list:
    just -l

# This creates a .venv folder - only used by vscode
venv:
    uv sync

# Run the agent in the CLI
[group('after-meeting')]
run-horseragish:
    uv run adk run horseragish/

# [👍] Runs ADK WEB
[group('after-meeting')]
run-horseragish-web:
    uv run adk web --reload --log_level info

# TODO implement this
# [group('after-meeting')]
# init:
#     echo "Initializing new world agents..."
# TODO make it work .


# [👍] Take me to github
[group('after-meeting')]
github:
    open https://github.com/palladius/ai-friendly-agents/tree/main/adk-test-agents/horseragish


# [👍] simple test for the max agent
[group('tests')]
test-riccardo-agent:
    echo 'how are you?' |adk run horseragish/horseragish_ricc/

# [👍] simple test for the max agent
[group('tests')]
test-max-agent:
    echo 'how are you?' |adk run horseragish/horseragish_max/

# [👍] Show Action Items on code
[group('tests')]
show-todos:
    @echo "TODOs in this project:"
    @echo "[🇮🇹] Searching for TODOs from RICC in the codebase..."
    @find . -maxdepth 3 -type f -name "*.py" -exec grep -H "TODO(ricc" {} \; || echo "🤷 No TODOs found => ricc rocks!"
    @echo "[🇫🇷] Searching for TODOs from MAX in the codebase..."
    @find . -maxdepth 3 -type f -name "*.py" -exec grep -H "TODO(max" {} \; || echo "🤷 No TODOs found => Max is a slacker"
# grep --exclude-dir={.venv} -r "TODO(max" . || echo "No TODOs found."

# 🧹 Cleans up Python bytecode and cache files
clean:
    @echo "🧹 Cleaning up Python bytecode and cache files. Size before the cure:"
    du -sh .
    find . -name "*.pyc" -delete
    find . -name "__pycache__" -delete
    find . -name ".pytest_cache" -delete
    find . -name ".venv" -delete
    find . -name ".mypy_cache" -delete
    @echo "🧹 Size AFTER the cure:"
    du -sh .

# [👍] This is another script Maxime will thank me for 😉 -> https://github.com/charmbracelet/glow
readme:
    cat README.md | glow -s dracula --width 100
