
source "https://rubygems.org"


#gem 'model_context_protocol'
#https://rubygems.org/gems/model-context-protocol-rb
#gem 'model-context-protocol-rb'
# https://rubygems.org/gems/model_context_protocol_riccardo copied from it.
gem 'model_context_protocol_riccardo'
