
list:
    just -l


ruby-server:
    bundle exec ruby stdio-serp-mcp.rb

python-stdio-client-to-rails-mcp-server:
    python python_agent_stdio.py

sample-client-question-to-SERP:
    echo "What is current date and time in Zurich (CH)?" |  python python_agent_stdio.py


connect-to-rails-mcp-server:
    python python_agent_http.py
