
source "https://rubygems.org"

gem "fast-mcp", "~> 1.4"
gem "google_search_results"

gem 'rack' # rack/handler/puma
gem 'puma'
gem 'rackup'

# remove me
#gem 'sinatra'
# gem 'sinatra-activerecord'
# gem 'sinatra-contrib'
# gem 'sinatra-static-assets'
