#source .envrc  # Loads your environment variables
set export
set dotenv-load

# Should get them from envrc...
#PROJECT_ID := "justfile_pincopallo"
#GCP_REGION := 'justfile-antarctica-east-1'

# Lists all targets
[group('default')]
list:
    @yellow "[justfile] SERP_API_KEY=$SERP_API_KEY"
    @just -l


# launches ruby MCP server (stdio or SSE?) on port 9292
[group('mcp')]
rack-server:
    env SERP_API_KEY="${SERP_API_KEY}" bundle exec ruby server.rb

# launches ruby MCP server over STDIO
[group('stdio')]
stdio-server:
    env SERP_API_KEY="${SERP_API_KEY}" bundle exec ruby stdio_server.rb

# tests it if SSE STDIO
# curl -X POST -H "Content-Type: application/json" -d '{"jsonrpc": "2.0", "id": "1", "method": "tools/list", "params": {} }' http://localhost:9292/mcp/messages
[group('mcp')]
test-sse-server:
    ./test-sse-and-messages-via-rpc.sh
    cat response-sse.json | jq -r '.result.tools[] | "\(.name) ➡️➡️ \(.description)"'

# tests it if STDIO
[group('stdio')]
test-stdio-server:
    echo '{"jsonrpc": "2.0", "id": "1", "method": "tools/list", "params": {} }'  |  just stdio-server  | tee response-stdio.json
    cat response-stdio.json | jq -r '.result.tools[] | "\(.name) ➡️➡️ \(.description)"'
