
#source .envrc  # Loads your environment variables
set export
set dotenv-load

# Should get them from envrc...
#PROJECT_ID := "justfile_pincopallo"
#GCP_REGION := 'justfile-antarctica-east-1'

# Lists all targets
[group('default')]
list:
    @yellow "[justfile] SERP_API_KEY=$SERP_API_KEY"
    @just -l


# launches ruby MCP server (stdio or SSE?) on port 9292
[group('mcp')]
rack-server:
    env SERP_API_KEY="${SERP_API_KEY}" bundle exec ruby server.rb

# tests it if STDIO
[group('mcp')]
test-server:
    echo '{"jsonrpc": "2.0", "id": "1", "method": "tools/list", "params": {} }'  |  nc localhost 9292  | tee response.json
    cat response.json | jq -r '.result.tools[] | "\(.name) ➡️➡️ \(.description)"'
