
list:
    just -l

# want to see quickstart client server apps: https://github.com/modelcontextprotocol/quickstart-resources/tree/main/weather-server-python
download-quickstart-resources:
    git clone https://github.com/modelcontextprotocol/quickstart-resources quickstart-resources-copy/


inspect-python-weather-server:
    npx @modelcontextprotocol/inspector \
        uv \
        --directory python/weather-server-python/ \
        run \
        weather


download-fast-mcp:
    git clone https://github.com/yjacquin/fast-mcp fast-mcp-copy/

clean:
    rm -rf quickstart-resources-copy
    rm -rf fast-mcp-copy
    # rm -rf python/weather-server-python/quickstart-resources-copy
    # rm -rf python/weather-server-python/fast-mcp-copy
    # rm -rf python/weather-server-python/quickstart-resources
