
list:
    just -l

run:
    python main.py

test-gpt:
    python gpt_agent.py
test-claude:
    python claude_agent.py
test-toolz:
    python toolz.py

# S3.4 -- Interact with the Agent Team
test-agent-interaction:
    python sub_agents.py

#  S4.3 -- Redefine Sub-Agents and Update Root Agent with output_key
test-4-3:
    python sub_agents_v2.py

# S4.4 Interact to Test State Flow and output_key
test-4-4:
    python s4_4_interactive_session.py


# Update Root Agent with before_model_callback (useless, just constructors)
test-5-2:
    python s5_2_block_guardrail.py

# Test the Tool Guardrail with both BeforeModel and BeforeTool callbacks.
test-6-3:
    python s6_3_before_tool_callback_guardrail.py
