
# Todo add .env here. copy from PROD

list:
    just -l
    # @echo GEMINI_API_KEY=$GEMINI_API_KEY

# Executes agents on web. Pretty sweet if you ask me.
web:
    adk web

run-weather:
    adk run quickstart_multi_tool_agent/

clean:
    find . -name "*.pyc" -delete
    find . -name "__pycache__" -delete
    find . -name ".pytest_cache" -delete
    find . -name ".mypy_cache" -delete

run-gemmina-050: clean
    which adk
    export OLLAMA_API_BASE="http://localhost:11434" && adk run gemmina-adk050/

adk-version:
    echo adk --version NON VA
    which adk
    cat $(which adk)
    ls -al "$(dirname $(which adk))"/../





# Ricc loves 🍕
[group('newworld')]
run-horseragish-ricc:
    adk run horseragish/horseragish_ricc/

# Max loves 🇫🇷
[group('newworld')]
run-horseragish-max:
    adk run horseragish/horseragish_max/

[group('newworld')]
init:
    echo "Initializing new world agents..."
# TODO make it work .
