

list:
    just -l

# Executes agents on web. Pretty sweet if you ask me.
web:
    adk web

run-weather:
    adk run quickstart_multi_tool_agent/

clean:
    find . -name "*.pyc" -delete
    find . -name "__pycache__" -delete
    find . -name ".pytest_cache" -delete
    find . -name ".mypy_cache" -delete
